name: CD-Train-and-Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - run: pip install -r requirements.txt
      - name: Train model
        run: python src/train.py
      - name: Guardrail metrics >= 0.80
        run: |
          python - << 'PY'
          import json
          m = json.load(open("metrics.json"))
          assert m["accuracy"] >= 0.80, f"Accuracy too low: {m['accuracy']}"
          print("Accuracy OK:", m["accuracy"])
          PY
      - uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            model.joblib
            metrics.json

  release:
    runs-on: ubuntu-latest
    needs: train
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: model-and-metrics
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/model.joblib
            dist/metrics.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
